default: &default
  adapter: postgresql
  encoding: unicode
#  host db is for docker dev env
#  host: db
  host: localhost
  username: postgres
  password: docker
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
