json.content node.content
json.created_ad node.created_at
json.graph_id node.graph_id
json.to_edge_ids node.to_edge_ids
json.id node.id
json.name node.name
json.type node.type
json.updated_at node.updated_at
json.x node.x
json.y node.y
